#!/bin/sh
#
# Startup script for the DNS caching server
#
# chkconfig: - 49 50
# description: This script starts dnsmasq for bare metal nodes PXE boot
# processname: dnsmasq
# pidfile: /var/run/dnsmasq-bm.pid

# Source function library.
. /etc/rc.d/init.d/functions

# Source networking configuration.
. /etc/sysconfig/network

# Check that networking is up.
[ ${NETWORKING} = "no" ] && exit 0

dnsmasq=/usr/sbin/dnsmasq
[ -f $dnsmasq ] || exit 0

pidfile=/var/run/dnsmasq-bm.pid
config=/etc/dnsmasq-bm.conf

DOMAIN_SUFFIX=`dnsdomainname`
if [ ! -z "${DOMAIN_SUFFIX}" ]; then
  OPTIONS="-s $DOMAIN_SUFFIX --pid-file=$pidfile --conf-file=$config"
fi

RETVAL=0

# See how we were called.
case "$1" in
  start)
        if [ $UID -ne 0 ] ; then
            echo "User has insufficient privilege."
            exit 4
        fi
        echo -n "Starting dnsmasq: "
        daemon $dnsmasq $OPTIONS
	RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && touch /var/lock/subsys/dnsmasq-bm
        ;;
  stop)
	killproc -p $pidfile dnsmasq
	RETVAL=$?
        echo
        [ $RETVAL -eq 0 ] && rm -f /var/lock/subsys/dnsmasq-bm /var/run/dnsmasq-bm.pid
        ;;
  status)
	status -p $pidfile dnsmasq
	RETVAL=$?
	;;
  reload)
	echo -n "Reloading dnsmasq: "
	killproc -p $pidfile dnsmasq -HUP
	RETVAL=$?
	echo
	;;
  force-reload)
        # new configuration takes effect only after restart
	$0 stop
	$0 start
	RETVAL=$?
        ;;
  restart)
	$0 stop
	$0 start
	RETVAL=$?
	;;
  *)
        echo "Usage: $0 {start|stop|restart|reload|status}"
        exit 2
esac

exit $RETVAL

